sonar.projectKey=scorpion-lone-wolf_mernspace-p-auth-service
sonar.organization=scorpion-lone-wolf

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/migrations/**
sonar.coverage.exclusions=src/server.ts,src/config/**,src/routes/**,src/schemas/**,src/types/**,src/entities/**,src/migrations/**,src/utils/index.ts

# wait untill sonar quality gate passes and if fail then whole workflow fails
sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=coverage/lcov.info
