sonar.projectKey=scorpion-lone-wolf_mernspace-p-auth-service
sonar.organization=scorpion-lone-wolf

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/migrations/**

# wait untill sonar quality gate passes and if fail then whole workflow fails
sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=coverage/lcov.info
